### ISSUE TITLE
Support for mongodb-memory-server version 7.x

### ISSUE THREAD

**Issue by LinusU** [lirbank/jest-environment-mongodb#14]
Version 7.x added support for my platform (arm64), but it doesn't seem like we are compatible with version 7.x yet. I'm getting the following error:

```text
  ● Test suite failed to run

    "instanceInfo" is undefined

      at assertionInstanceInfo (node_modules/mongodb-memory-server-core/src/MongoMemoryServer.ts:721:38)
      at MongoMemoryServer.getUri (node_modules/mongodb-memory-server-core/src/MongoMemoryServer.ts:632:5)
      at EphemeralEnvironment.setup (node_modules/jest-environment-mongodb/src/index.ts:46:47)
```

related: https://github.com/nodkz/mongodb-memory-server/issues/213

**Comment by Snitovets** [comment]
from 7.x.x versions MongoMemoryServer instance have to starts manually:

```
mongod = new MongoMemoryServer();
await mongod.start();

const mongoUri = mongo.getUri();

await mongoose.connect(mongoUri, {
	useCreateIndex: true,
	useNewUrlParser: true,
	useUnifiedTopology: true
});
```

**Comment by boredland** [comment]
Hi there! Created a PR that should squash all the deprecations at once, including this one. Would appreciate a review! https://github.com/lirbank/jest-environment-mongodb/pull/28
